#!/usr/bin/env python

import gtk, time, pygst, gst
class Player:
	def __init__(self):
		self.fritz=('mms://stream2.rbb-online.de/wmtencoder/fritz-live-backup.wma')
		self.dradio=('http://dradio-ogg.t-bn.de/dlf_high.ogg')
		self.dradiow=('http://dradio.ic.llnwd.net/stream/dradio_dwissen_m_a.ogg')
		self.player = gst.element_factory_make("playbin","player")
		bus = self.player.get_bus()
		bus.add_signal_watch()
		bus.connect("message", self.on_message)
	
	def playdradio(self,chan):
		self.player.set_state(gst.STATE_NULL)
		self.player.set_property("uri",self.dradio)
		self.player.set_state(gst.STATE_PLAYING)

	def playfritz(self,chan):
		self.player.set_state(gst.STATE_NULL)
		self.player.set_property("uri",self.fritz)
		self.player.set_state(gst.STATE_PLAYING)
	
	def playdradiow(self,chan):
		self.player.set_state(gst.STATE_NULL)
		self.player.set_property("uri",self.dradiow)
		self.player.set_state(gst.STATE_PLAYING)

	def on_message(self,bus,message):
		t = message.type
		if t == gst.MESSAGE_EOS:
			self.player.set_state(gst.STATE_NULL)
		elif t == gst.MESSAGE_ERROR:
			self.player.set_state(gst.STATE_NULL)
			err, debug = message.parse_error()
			print "Error: %s" % err, debug

class RadioMenu(gtk.Menu):
	def __init__(self):
		gtk.Menu.__init__(self)
	       	self.radio = Player()	

		item = gtk.ImageMenuItem('Dradio')
		item.connect('activate', self.radio.playdradio)
		item.set_image(gtk.image_new_from_stock('gtk-media-play', gtk.ICON_SIZE_MENU))
		self.append(item)


		item = gtk.ImageMenuItem('Fritz')
		item.connect('activate', self.radio.playfritz)
		item.set_image(gtk.image_new_from_stock('gtk-media-play', gtk.ICON_SIZE_MENU))
		self.append(item)

		
                
		item = gtk.ImageMenuItem('Dradio W')
                item.connect('activate', self.radio.playdradiow)
                item.set_image(gtk.image_new_from_stock('gtk-media-play', gtk.ICON_SIZE_MENU))
		self.append(item)

		item = gtk.ImageMenuItem('exit')
		item.connect('activate', gtk.main_quit)
		item.set_image(gtk.image_new_from_stock('gtk-quit',gtk.ICON_SIZE_MENU))
		self.append(item)


	def show_menu(self, widget, button, time):
			self.show_all()
			self.popup(None, None, gtk.status_icon_position_menu, button, time, icon)




icon = gtk.status_icon_new_from_file('/usr/share/icons/gnome/24x24/devices/gnome-dev-wavelan.png')
icon.set_tooltip('Radio switcher')
player = Player()
menu = RadioMenu()
icon.connect("popup-menu",menu.show_menu)
gtk.main()
